# Generated by Django 4.0.1 on 2022-03-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('college', models.CharField(max_length=255, null=True)),
                ('university', models.CharField(max_length=255, null=True)),
                ('current_company', models.CharField(max_length=255, null=True)),
                ('hobbies', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
